
parameters:
  - in: body
    name: crwaling_config
    description: "The configuration for the crawling process."
    schema:
      $ref: '#/definitions/CrawlingConfig'


definitions:
  CrawlingConfig:
    type: object
    properties:
      nodes:
        description: "The type of nodes you want to be added to graph once scraped. Options for now is only email."
        type: array
        items:
          type: string
          example: "email"
      seeds:
        description: "The seeds to start the crawling from"
        type: array
        items:
          type: string
          example: "https://www.miet.ac.in"

responses:
  200:
    description: "A json file representing the crawling result which is a web graph."
    schema:
      type: object
      properties:
          links:
            type: array
            items:
              type: object
              example: {"source": "miet.ac.in", "target": "miet.ac.in", "weight": "0"}

          directed:
            description: "Whether the graph is directed or not."
            type: boolean
            example: true
          multigraph:
              description: "Whether the graph is a multigraph or not."
              type: boolean
              example: false
          graph:
            type: array
            example: []
          nodes:
            description: "The nodes of the graph."
            type: array
            items:
              type: object
              example: {"id": "miet.ac.in", "domain": "miet.ac.in", "type":"url"}

